## Unary Expression
	<unary_expr> ::= <unary_positive_expr> | <unary_negative_expr>
	<unary_positive_expr> ::= +<unary_term>
	<unary_positive_term> ::= <integer> | <float>
	<unary_negative_expr> ::= -<unary_negative_term>
	<unary_negative_term> ::= <non_neg_integer> | <non_neg_float> | (<neg_integer>) | (<neg_float>)
	### Edge Case: -(<neg_integer>) instead of -<neg_integer>, -(<neg_float>) instead of -<neg_float>
## Arithmetic Expression
	<arithmetic_expr> ::= <arithmetic_expr> <arithmetic_operator> <arithmetic_expr> | <arithmetic_term> | (<arithmetic_expr>)
	<arithmetic_term> ::= <integer> | <float>
	<arithmetic_operator> ::= + | - | * | /
## List Expression
	<list_expr> ::= <list> | <list_concatenation_expr> | <list_subtraction_expr> | (<list_expr>)
	<list_concatenation_expr> ::= <list_expr> ++ <list_expr> || <list_expr> ++ <term> 
	<list_subtraction_expr> ::= <list_expr> -- <list_expr>
## Boolean Expression
	<boolean_expr> ::= <strict_boolean_expr> | <relaxed_boolean_expr> | <relaxed_boolean_term> | <not_boolean_expr> | (<boolean_expr>)
	<not_boolean_expr> ::= not(<boolean_expr>) | !<boolean_expr>
	<relaxed_boolean_expr> ::= <boolean_expr> <relaxed_boolean_operator> <boolean_expr>
	<strict_boolean_expr> ::= <strict_boolean_term> <strict_boolean_operator> <boolean_expr>
	<relaxed_boolean_operator> ::= && | ||
	<strict_boolean_operator> ::= and | or
	<strict_boolean_term> ::= <boolean>
	<relaxed_boolean_term> ::= <term>
## Membership Expression
	<membership_in_expr> ::= <element> in <collection>
	<membership_notin_expr> ::= <element> not in <collection>
	<element> ::= <term>
	<collection> ::= <list> | <range_expr>
## Range Expression
	<range_expr> ::= <range_term>..<range_term>
	<range_term> ::= <integer> | <function_expr>
## Binary Concatenation Expression
	<binary_concatenation_expr> ::= <binary> | <binary_concatenation_expr> <> <binary>
## Pipeline Expression
	<pipeline_expr> ::= <expr> |> <pipeline_term>
	<pipeline_term> ::= <function_expr> | <function_expr> |> <pipeline_term>
## Text-based Match Expression
	<text_match_expr> ::= <string> =~ <string> | <regex>
## Pin Expression
<pin_expr> ::= ^<term> = <term>
## Match Expression
<match_expr> ::= <term> = <term>
## Comparison Expression
	<comparison_expr> :: <term> <comparison_operator> <term>
	<comparison_operator> :: == | === | != | !== | < | > | <= | >=
!! . - dot operator
!! :: - type operator
!! => - see %{}
!! <- - see for and with
